; sleep.g
; called when M1 (Sleep) is being processed
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Sun Feb 09 2020 08:41:29 GMT-0600 (Central Standard Time)
M81 S1 ; Shutdown after cooling

